### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by JingerYu** [PanagiwtisR/5G_SDN_VANET#1]
Traceback (most recent call last):
  File "multi-c-approach_bandwidth.py", line 8, in <module>
    from mn_wifi.cli import CLI_wifi
ImportError: cannot import name CLI_wifi

- There is a error when I run "python multi-c-approach_bandwidth.py"

- and there is another error when I start the RYU with “wifi.py"

Traceback (most recent call last):
  File "wifi.py", line 27, in <module>
    from ryu.lib.packet import wifi
ImportError: cannot import name wifi

there is not "wifi.py" in ryu.lib.packet
and there is not "CLI_wifi" in mn_wifi.cli

**Comment by frostbyte012** [comment]
I have the same issue.

**Comment by frostbyte012** [comment]
@JingerYu  Did u get any solution regarding it?
